name: PR 🚀

on:
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run PEP8
        id: auto-pep8
        uses: peter-evans/autopep8@v2
        with:
          args: --recursive --in-place --aggressive --aggressive .

      - name: Fail for PEP8 violations
        if: steps.auto-pep8.outputs.exit-code == 2
        run: exit 1
