name: Release 🚢

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package plugin
        run: git archive --prefix=rigacar/ --format=zip HEAD -o rigacar-${{ github.ref_name }}.zip

      - name: Attach to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: rigacar-${{ github.ref_name }}.zip
